### ISSUE TITLE
Failed to install this pack with st2-docker

### ISSUE THREAD

**Issue by brainstorm** [StackStorm-Exchange/stackstorm-ansible#23]
There seems to be an issue with the kerberos extension and its dependencies (gssapi.h):

```
$ docker exec -it stackstorm /bin/bash
ckstorm-ansible02:/# st2 pack install https://github.com/StackStorm-Exchange/sta

	[ succeeded ] download pack
	[ succeeded ] make a prerun
	[  failed   ] install pack dependencies

id: 5a277319d6874c00d0070577
action.ref: packs.install
parameters:
  packs:
  - https://github.com/StackStorm-Exchange/stackstorm-ansible
status: failed
result_task: install pack dependencies
result:
  exit_code: 1
  result: None
  stderr: "st2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Setting up virtualenv for pack \"ansible\" (/opt/stackstorm/packs/ansible)\nst2.actions.python.SetupVirtualEnvironmentAction: INFO     Virtualenv path \"/opt/stackstorm/virtualenvs/ansible\" doesn't exist\nst2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Creating virtualenv for pack \"ansible\" in \"/opt/stackstorm/virtualenvs/ansible\"\nst2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Creating virtualenv in \"/opt/stackstorm/virtualenvs/ansible\" using Python binary \"/opt/stackstorm/st2/bin/python\"\nst2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Running command \"/opt/stackstorm/st2/bin/virtualenv -p /opt/stackstorm/st2/bin/python --always-copy /opt/stackstorm/virtualenvs/ansible\" to create virtualenv.\nst2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Installing base requirements\nst2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Installing requirement six>=1.9.0,<2.0 with command /opt/stackstorm/virtualenvs/ansible/bin/pip install six>=1.9.0,<2.0.\nst2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Installing pack specific requirements from \"/opt/stackstorm/packs/ansible/requirements.txt\"\nst2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Installing requirements from file /opt/stackstorm/packs/ansible/requirements.txt with command /opt/stackstorm/virtualenvs/ansible/bin/pip install -U -r /opt/stackstorm/packs/ansible/requirements.txt.\nTraceback (most recent call last):\n  File \"/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/runners/python_action_wrapper.py\", line 259, in <module>\n    obj.run()\n  File \"/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/runners/python_action_wrapper.py\", line 155, in run\n    output = action.run(**self._parameters)\n  File \"/opt/stackstorm/packs/packs/actions/pack_mgmt/setup_virtualenv.py\", line 88, in run\n    proxy_config=self.proxy_config)\n  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/util/virtualenvs.py\", line 102, in setup_pack_virtualenv\n    logger=logger)\n  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/util/virtualenvs.py\", line 222, in install_requirements\n    (requirements_file_path, stdout, stderr))\nException: Failed to install requirements from \"/opt/stackstorm/packs/ansible/requirements.txt\": Collecting ansible>=1.9 (from -r /opt/stackstorm/packs/ansible/requirements.txt (line 1))\n  Downloading ansible-2.4.2.0.tar.gz (6.5MB)\nCollecting pywinrm[credssp,kerberos]>=0.2.2 (from -r /opt/stackstorm/packs/ansible/requirements.txt (line 2))\n  Downloading pywinrm-0.2.2-py2.py3-none-any.whl\nCollecting jinja2 (from ansible>=1.9->-r /opt/stackstorm/packs/ansible/requirements.txt (line 1))\n  Downloading Jinja2-2.10-py2.py3-none-any.whl (126kB)\nCollecting PyYAML (from ansible>=1.9->-r /opt/stackstorm/packs/ansible/requirements.txt (line 1))\nCollecting paramiko (from ansible>=1.9->-r /opt/stackstorm/packs/ansible/requirements.txt (line 1))\n  Downloading paramiko-2.4.0-py2.py3-none-any.whl (192kB)\nCollecting cryptography (from ansible>=1.9->-r /opt/stackstorm/packs/ansible/requirements.txt (line 1))\n  Downloading cryptography-2.1.4-cp27-cp27mu-manylinux1_x86_64.whl (2.2MB)\nRequirement already up-to-date: setuptools in /opt/stackstorm/virtualenvs/ansible/lib/python2.7/site-packages (from ansible>=1.9->-r /opt/stackstorm/packs/ansible/requirements.txt (line 1))\nCollecting xmltodict (from pywinrm[credssp,kerberos]>=0.2.2->-r /opt/stackstorm/packs/ansible/requirements.txt (line 2))\n  Downloading xmltodict-0.11.0-py2.py3-none-any.whl\nCollecting requests-ntlm>=0.3.0 (from pywinrm[credssp,kerberos]>=0.2.2->-r /opt/stackstorm/packs/ansible/requirements.txt (line 2))\n  Downloading requests_ntlm-1.1.0-py2.py3-none-any.whl\nRequirement already up-to-date: six in /opt/stackstorm/virtualenvs/ansible/lib/python2.7/site-packages (from pywinrm[credssp,kerberos]>=0.2.2->-r /opt/stackstorm/packs/ansible/requirements.txt (line 2))\nCollecting requests>=2.9.1 (from pywinrm[credssp,kerberos]>=0.2.2->-r /opt/stackstorm/packs/ansible/requirements.txt (line 2))\n  Using cached requests-2.18.4-py2.py3-none-any.whl\nCollecting requests-credssp>=0.0.1; extra == \"credssp\" (from pywinrm[credssp,kerberos]>=0.2.2->-r /opt/stackstorm/packs/ansible/requirements.txt (line 2))\n  Downloading requests_credssp-0.1.0-py2.py3-none-any.whl\nCollecting requests-kerberos>=0.10.0; extra == \"kerberos\" (from pywinrm[credssp,kerberos]>=0.2.2->-r /opt/stackstorm/packs/ansible/requirements.txt (line 2))\n  Downloading requests_kerberos-0.11.0-py2.py3-none-any.whl\nCollecting MarkupSafe>=0.23 (from jinja2->ansible>=1.9->-r /opt/stackstorm/packs/ansible/requirements.txt (line 1))\n  Downloading MarkupSafe-1.0.tar.gz\nCollecting pynacl>=1.0.1 (from paramiko->ansible>=1.9->-r /opt/stackstorm/packs/ansible/requirements.txt (line 1))\n  Downloading PyNaCl-1.2.1-cp27-cp27mu-manylinux1_x86_64.whl (696kB)\nCollecting bcrypt>=3.1.3 (from paramiko->ansible>=1.9->-r /opt/stackstorm/packs/ansible/requirements.txt (line 1))\n  Downloading bcrypt-3.1.4-cp27-cp27mu-manylinux1_x86_64.whl (57kB)\nCollecting pyasn1>=0.1.7 (from paramiko->ansible>=1.9->-r /opt/stackstorm/packs/ansible/requirements.txt (line 1))\n  Downloading pyasn1-0.4.2-py2.py3-none-any.whl (71kB)\nCollecting cffi>=1.7; platform_python_implementation != \"PyPy\" (from cryptography->ansible>=1.9->-r /opt/stackstorm/packs/ansible/requirements.txt (line 1))\n  Downloading cffi-1.11.2-cp27-cp27mu-manylinux1_x86_64.whl (405kB)\nCollecting enum34; python_version < \"3\" (from cryptography->ansible>=1.9->-r /opt/stackstorm/packs/ansible/requirements.txt (line 1))\n  Using cached enum34-1.1.6-py2-none-any.whl\nCollecting idna>=2.1 (from cryptography->ansible>=1.9->-r /opt/stackstorm/packs/ansible/requirements.txt (line 1))\n  Using cached idna-2.6-py2.py3-none-any.whl\nCollecting asn1crypto>=0.21.0 (from cryptography->ansible>=1.9->-r /opt/stackstorm/packs/ansible/requirements.txt (line 1))\n  Downloading asn1crypto-0.23.0-py2.py3-none-any.whl (99kB)\nCollecting ipaddress; python_version < \"3\" (from cryptography->ansible>=1.9->-r /opt/stackstorm/packs/ansible/requirements.txt (line 1))\n  Downloading ipaddress-1.0.18-py2-none-any.whl\nCollecting ntlm-auth>=1.0.2 (from requests-ntlm>=0.3.0->pywinrm[credssp,kerberos]>=0.2.2->-r /opt/stackstorm/packs/ansible/requirements.txt (line 2))\n  Downloading ntlm_auth-1.0.6-py2.py3-none-any.whl\nCollecting urllib3<1.23,>=1.21.1 (from requests>=2.9.1->pywinrm[credssp,kerberos]>=0.2.2->-r /opt/stackstorm/packs/ansible/requirements.txt (line 2))\n  Using cached urllib3-1.22-py2.py3-none-any.whl\nCollecting chardet<3.1.0,>=3.0.2 (from requests>=2.9.1->pywinrm[credssp,kerberos]>=0.2.2->-r /opt/stackstorm/packs/ansible/requirements.txt (line 2))\n  Using cached chardet-3.0.4-py2.py3-none-any.whl\nCollecting certifi>=2017.4.17 (from requests>=2.9.1->pywinrm[credssp,kerberos]>=0.2.2->-r /opt/stackstorm/packs/ansible/requirements.txt (line 2))\n  Using cached certifi-2017.11.5-py2.py3-none-any.whl\nCollecting pyOpenSSL>=16.0.0 (from requests-credssp>=0.0.1; extra == \"credssp\"->pywinrm[credssp,kerberos]>=0.2.2->-r /opt/stackstorm/packs/ansible/requirements.txt (line 2))\n  Downloading pyOpenSSL-17.5.0-py2.py3-none-any.whl (53kB)\nCollecting pykerberos<2.0.0,>=1.1.8; sys_platform != \"win32\" (from requests-kerberos>=0.10.0; extra == \"kerberos\"->pywinrm[credssp,kerberos]>=0.2.2->-r /opt/stackstorm/packs/ansible/requirements.txt (line 2))\n  Downloading pykerberos-1.1.14.tar.gz\nCollecting pycparser (from cffi>=1.7; platform_python_implementation != \"PyPy\"->cryptography->ansible>=1.9->-r /opt/stackstorm/packs/ansible/requirements.txt (line 1))\n  Downloading pycparser-2.18.tar.gz (245kB)\nBuilding wheels for collected packages: ansible, MarkupSafe, pykerberos, pycparser\n  Running setup.py bdist_wheel for ansible: started\n  Running setup.py bdist_wheel for ansible: finished with status 'done'\n  Stored in directory: /root/.cache/pip/wheels/82/72/89/bcdf63814af976426a34174577b5775d8604b268b1b21fdc1a\n  Running setup.py bdist_wheel for MarkupSafe: started\n  Running setup.py bdist_wheel for MarkupSafe: finished with status 'done'\n  Stored in directory: /root/.cache/pip/wheels/88/a7/30/e39a54a87bcbe25308fa3ca64e8ddc75d9b3e5afa21ee32d57\n  Running setup.py bdist_wheel for pykerberos: started\n  Running setup.py bdist_wheel for pykerberos: finished with status 'error'\n  Complete output from command /opt/stackstorm/virtualenvs/ansible/bin/python -u -c \"import setuptools, tokenize;__file__='/tmp/pip-build-bJBxdS/pykerberos/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\\r\\n', '\\n');f.close();exec(compile(code, __file__, 'exec'))\" bdist_wheel -d /tmp/tmpghrygfpip-wheel- --python-tag cp27:\n  running bdist_wheel\n  running build\n  running build_ext\n  building 'kerberos' extension\n  creating build\n  creating build/temp.linux-x86_64-2.7\n  creating build/temp.linux-x86_64-2.7/src\n  x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c src/kerberos.c -o build/temp.linux-x86_64-2.7/src/kerberos.o\n  In file included from src/kerberos.c:19:0:\n  src/kerberosbasic.h:17:27: fatal error: gssapi/gssapi.h: No such file or directory\n   #include <gssapi/gssapi.h>\n                             ^\n  compilation terminated.\n  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1\n  \n  ----------------------------------------\n  Running setup.py clean for pykerberos\n  Running setup.py bdist_wheel for pycparser: started\n  Running setup.py bdist_wheel for pycparser: finished with status 'done'\n  Stored in directory: /root/.cache/pip/wheels/95/14/9a/5e7b9024459d2a6600aaa64e0ba485325aff7a9ac7489db1b6\nSuccessfully built ansible MarkupSafe pycparser\nFailed to build pykerberos\nInstalling collected packages: MarkupSafe, jinja2, PyYAML, pycparser, cffi, pynacl, enum34, idna, asn1crypto, ipaddress, cryptography, bcrypt, pyasn1, paramiko, ansible, xmltodict, ntlm-auth, urllib3, chardet, certifi, requests, requests-ntlm, pyOpenSSL, requests-credssp, pykerberos, requests-kerberos, pywinrm\n  Running setup.py install for pykerberos: started\n    Running setup.py install for pykerberos: finished with status 'error'\n    Complete output from command /opt/stackstorm/virtualenvs/ansible/bin/python -u -c \"import setuptools, tokenize;__file__='/tmp/pip-build-bJBxdS/pykerberos/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\\r\\n', '\\n');f.close();exec(compile(code, __file__, 'exec'))\" install --record /tmp/pip-NrK7Jm-record/install-record.txt --single-version-externally-managed --compile --install-headers /opt/stackstorm/virtualenvs/ansible/include/site/python2.7/pykerberos:\n    running install\n    running build\n    running build_ext\n    building 'kerberos' extension\n    creating build\n    creating build/temp.linux-x86_64-2.7\n    creating build/temp.linux-x86_64-2.7/src\n    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c src/kerberos.c -o build/temp.linux-x86_64-2.7/src/kerberos.o\n    In file included from src/kerberos.c:19:0:\n    src/kerberosbasic.h:17:27: fatal error: gssapi/gssapi.h: No such file or directory\n     #include <gssapi/gssapi.h>\n                               ^\n    compilation terminated.\n    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1\n    \n    ----------------------------------------\n (stderr: /opt/stackstorm/virtualenvs/ansible/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.\n  SNIMissingWarning\n/opt/stackstorm/virtualenvs/ansible/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.\n  InsecurePlatformWarning\n  Failed building wheel for pykerberos\nCommand \"/opt/stackstorm/virtualenvs/ansible/bin/python -u -c \"import setuptools, tokenize;__file__='/tmp/pip-build-bJBxdS/pykerberos/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\\r\\n', '\\n');f.close();exec(compile(code, __file__, 'exec'))\" install --record /tmp/pip-NrK7Jm-record/install-record.txt --single-version-externally-managed --compile --install-headers /opt/stackstorm/virtualenvs/ansible/include/site/python2.7/pykerberos\" failed with error code 1 in /tmp/pip-build-bJBxdS/pykerberos/\n)\n"
  stdout: ''
error: st2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Setting up virtualenv for pack "ansible" (/opt/stackstorm/packs/ansible)
st2.actions.python.SetupVirtualEnvironmentAction: INFO     Virtualenv path "/opt/stackstorm/virtualenvs/ansible" doesn't exist
st2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Creating virtualenv for pack "ansible" in "/opt/stackstorm/virtualenvs/ansible"
st2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Creating virtualenv in "/opt/stackstorm/virtualenvs/ansible" using Python binary "/opt/stackstorm/st2/bin/python"
st2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Running command "/opt/stackstorm/st2/bin/virtualenv -p /opt/stackstorm/st2/bin/python --always-copy /opt/stackstorm/virtualenvs/ansible" to create virtualenv.
st2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Installing base requirements
st2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Installing requirement six>=1.9.0,<2.0 with command /opt/stackstorm/virtualenvs/ansible/bin/pip install six>=1.9.0,<2.0.
st2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Installing pack specific requirements from "/opt/stackstorm/packs/ansible/requirements.txt"
st2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Installing requirements from file /opt/stackstorm/packs/ansible/requirements.txt with command /opt/stackstorm/virtualenvs/ansible/bin/pip install -U -r /opt/stackstorm/packs/ansible/requirements.txt.
Traceback (most recent call last):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/runners/python_action_wrapper.py", line 259, in <module>
    obj.run()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/runners/python_action_wrapper.py", line 155, in run
    output = action.run(**self._parameters)
  File "/opt/stackstorm/packs/packs/actions/pack_mgmt/setup_virtualenv.py", line 88, in run
    proxy_config=self.proxy_config)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/util/virtualenvs.py", line 102, in setup_pack_virtualenv
    logger=logger)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/util/virtualenvs.py", line 222, in install_requirements
    (requirements_file_path, stdout, stderr))
Exception: Failed to install requirements from "/opt/stackstorm/packs/ansible/requirements.txt": Collecting ansible>=1.9 (from -r /opt/stackstorm/packs/ansible/requirements.txt (line 1))
  Downloading ansible-2.4.2.0.tar.gz (6.5MB)
Collecting pywinrm[credssp,kerberos]>=0.2.2 (from -r /opt/stackstorm/packs/ansible/requirements.txt (line 2))
  Downloading pywinrm-0.2.2-py2.py3-none-any.whl
Collecting jinja2 (from ansible>=1.9->-r /opt/stackstorm/packs/ansible/requirements.txt (line 1))
  Downloading Jinja2-2.10-py2.py3-none-any.whl (126kB)
Collecting PyYAML (from ansible>=1.9->-r /opt/stackstorm/packs/ansible/requirements.txt (line 1))
Collecting paramiko (from ansible>=1.9->-r /opt/stackstorm/packs/ansible/requirements.txt (line 1))
  Downloading paramiko-2.4.0-py2.py3-none-any.whl (192kB)
Collecting cryptography (from ansible>=1.9->-r /opt/stackstorm/packs/ansible/requirements.txt (line 1))
  Downloading cryptography-2.1.4-cp27-cp27mu-manylinux1_x86_64.whl (2.2MB)
Requirement already up-to-date: setuptools in /opt/stackstorm/virtualenvs/ansible/lib/python2.7/site-packages (from ansible>=1.9->-r /opt/stackstorm/packs/ansible/requirements.txt (line 1))
Collecting xmltodict (from pywinrm[credssp,kerberos]>=0.2.2->-r /opt/stackstorm/packs/ansible/requirements.txt (line 2))
  Downloading xmltodict-0.11.0-py2.py3-none-any.whl
Collecting requests-ntlm>=0.3.0 (from pywinrm[credssp,kerberos]>=0.2.2->-r /opt/stackstorm/packs/ansible/requirements.txt (line 2))
  Downloading requests_ntlm-1.1.0-py2.py3-none-any.whl
Requirement already up-to-date: six in /opt/stackstorm/virtualenvs/ansible/lib/python2.7/site-packages (from pywinrm[credssp,kerberos]>=0.2.2->-r /opt/stackstorm/packs/ansible/requirements.txt (line 2))
Collecting requests>=2.9.1 (from pywinrm[credssp,kerberos]>=0.2.2->-r /opt/stackstorm/packs/ansible/requirements.txt (line 2))
  Using cached requests-2.18.4-py2.py3-none-any.whl
Collecting requests-credssp>=0.0.1; extra == "credssp" (from pywinrm[credssp,kerberos]>=0.2.2->-r /opt/stackstorm/packs/ansible/requirements.txt (line 2))
  Downloading requests_credssp-0.1.0-py2.py3-none-any.whl
Collecting requests-kerberos>=0.10.0; extra == "kerberos" (from pywinrm[credssp,kerberos]>=0.2.2->-r /opt/stackstorm/packs/ansible/requirements.txt (line 2))
  Downloading requests_kerberos-0.11.0-py2.py3-none-any.whl
Collecting MarkupSafe>=0.23 (from jinja2->ansible>=1.9->-r /opt/stackstorm/packs/ansible/requirements.txt (line 1))
  Downloading MarkupSafe-1.0.tar.gz
Collecting pynacl>=1.0.1 (from paramiko->ansible>=1.9->-r /opt/stackstorm/packs/ansible/requirements.txt (line 1))
  Downloading PyNaCl-1.2.1-cp27-cp27mu-manylinux1_x86_64.whl (696kB)
Collecting bcrypt>=3.1.3 (from paramiko->ansible>=1.9->-r /opt/stackstorm/packs/ansible/requirements.txt (line 1))
  Downloading bcrypt-3.1.4-cp27-cp27mu-manylinux1_x86_64.whl (57kB)
Collecting pyasn1>=0.1.7 (from paramiko->ansible>=1.9->-r /opt/stackstorm/packs/ansible/requirements.txt (line 1))
  Downloading pyasn1-0.4.2-py2.py3-none-any.whl (71kB)
Collecting cffi>=1.7; platform_python_implementation != "PyPy" (from cryptography->ansible>=1.9->-r /opt/stackstorm/packs/ansible/requirements.txt (line 1))
  Downloading cffi-1.11.2-cp27-cp27mu-manylinux1_x86_64.whl (405kB)
Collecting enum34; python_version < "3" (from cryptography->ansible>=1.9->-r /opt/stackstorm/packs/ansible/requirements.txt (line 1))
  Using cached enum34-1.1.6-py2-none-any.whl
Collecting idna>=2.1 (from cryptography->ansible>=1.9->-r /opt/stackstorm/packs/ansible/requirements.txt (line 1))
  Using cached idna-2.6-py2.py3-none-any.whl
Collecting asn1crypto>=0.21.0 (from cryptography->ansible>=1.9->-r /opt/stackstorm/packs/ansible/requirements.txt (line 1))
  Downloading asn1crypto-0.23.0-py2.py3-none-any.whl (99kB)
Collecting ipaddress; python_version < "3" (from cryptography->ansible>=1.9->-r /opt/stackstorm/packs/ansible/requirements.txt (line 1))
  Downloading ipaddress-1.0.18-py2-none-any.whl
Collecting ntlm-auth>=1.0.2 (from requests-ntlm>=0.3.0->pywinrm[credssp,kerberos]>=0.2.2->-r /opt/stackstorm/packs/ansible/requirements.txt (line 2))
  Downloading ntlm_auth-1.0.6-py2.py3-none-any.whl
Collecting urllib3<1.23,>=1.21.1 (from requests>=2.9.1->pywinrm[credssp,kerberos]>=0.2.2->-r /opt/stackstorm/packs/ansible/requirements.txt (line 2))
  Using cached urllib3-1.22-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.9.1->pywinrm[credssp,kerberos]>=0.2.2->-r /opt/stackstorm/packs/ansible/requirements.txt (line 2))
  Using cached chardet-3.0.4-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests>=2.9.1->pywinrm[credssp,kerberos]>=0.2.2->-r /opt/stackstorm/packs/ansible/requirements.txt (line 2))
  Using cached certifi-2017.11.5-py2.py3-none-any.whl
Collecting pyOpenSSL>=16.0.0 (from requests-credssp>=0.0.1; extra == "credssp"->pywinrm[credssp,kerberos]>=0.2.2->-r /opt/stackstorm/packs/ansible/requirements.txt (line 2))
  Downloading pyOpenSSL-17.5.0-py2.py3-none-any.whl (53kB)
Collecting pykerberos<2.0.0,>=1.1.8; sys_platform != "win32" (from requests-kerberos>=0.10.0; extra == "kerberos"->pywinrm[credssp,kerberos]>=0.2.2->-r /opt/stackstorm/packs/ansible/requirements.txt (line 2))
  Downloading pykerberos-1.1.14.tar.gz
Collecting pycparser (from cffi>=1.7; platform_python_implementation != "PyPy"->cryptography->ansible>=1.9->-r /opt/stackstorm/packs/ansible/requirements.txt (line 1))
  Downloading pycparser-2.18.tar.gz (245kB)
Building wheels for collected packages: ansible, MarkupSafe, pykerberos, pycparser
  Running setup.py bdist_wheel for ansible: started
  Running setup.py bdist_wheel for ansible: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/82/72/89/bcdf63814af976426a34174577b5775d8604b268b1b21fdc1a
  Running setup.py bdist_wheel for MarkupSafe: started
  Running setup.py bdist_wheel for MarkupSafe: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/88/a7/30/e39a54a87bcbe25308fa3ca64e8ddc75d9b3e5afa21ee32d57
  Running setup.py bdist_wheel for pykerberos: started
  Running setup.py bdist_wheel for pykerberos: finished with status 'error'
  Complete output from command /opt/stackstorm/virtualenvs/ansible/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-bJBxdS/pykerberos/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('
', '
');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpghrygfpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_ext
  building 'kerberos' extension
  creating build
  creating build/temp.linux-x86_64-2.7
  creating build/temp.linux-x86_64-2.7/src
  x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c src/kerberos.c -o build/temp.linux-x86_64-2.7/src/kerberos.o
  In file included from src/kerberos.c:19:0:
  src/kerberosbasic.h:17:27: fatal error: gssapi/gssapi.h: No such file or directory
   #include <gssapi/gssapi.h>
                             ^
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

  ----------------------------------------
  Running setup.py clean for pykerberos
  Running setup.py bdist_wheel for pycparser: started
  Running setup.py bdist_wheel for pycparser: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/95/14/9a/5e7b9024459d2a6600aaa64e0ba485325aff7a9ac7489db1b6
Successfully built ansible MarkupSafe pycparser
Failed to build pykerberos
Installing collected packages: MarkupSafe, jinja2, PyYAML, pycparser, cffi, pynacl, enum34, idna, asn1crypto, ipaddress, cryptography, bcrypt, pyasn1, paramiko, ansible, xmltodict, ntlm-auth, urllib3, chardet, certifi, requests, requests-ntlm, pyOpenSSL, requests-credssp, pykerberos, requests-kerberos, pywinrm
  Running setup.py install for pykerberos: started
    Running setup.py install for pykerberos: finished with status 'error'
    Complete output from command /opt/stackstorm/virtualenvs/ansible/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-bJBxdS/pykerberos/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('
', '
');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-NrK7Jm-record/install-record.txt --single-version-externally-managed --compile --install-headers /opt/stackstorm/virtualenvs/ansible/include/site/python2.7/pykerberos:
    running install
    running build
    running build_ext
    building 'kerberos' extension
    creating build
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/src
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c src/kerberos.c -o build/temp.linux-x86_64-2.7/src/kerberos.o
    In file included from src/kerberos.c:19:0:
    src/kerberosbasic.h:17:27: fatal error: gssapi/gssapi.h: No such file or directory
     #include <gssapi/gssapi.h>
                               ^
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

    ----------------------------------------
 (stderr: /opt/stackstorm/virtualenvs/ansible/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/opt/stackstorm/virtualenvs/ansible/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Failed building wheel for pykerberos
Command "/opt/stackstorm/virtualenvs/ansible/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-bJBxdS/pykerberos/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('
', '
');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-NrK7Jm-record/install-record.txt --single-version-externally-managed --compile --install-headers /opt/stackstorm/virtualenvs/ansible/include/site/python2.7/pykerberos" failed with error code 1 in /tmp/pip-build-bJBxdS/pykerberos/
)

traceback: None
failed_on: install pack dependencies
start_timestamp: 2017-12-06T04:33:29.375003Z
end_timestamp: 2017-12-06T04:34:22.350326Z
+--------------------------+------------------------+------+--------+-----------------+
| id                       | status                 | task | action | start_timestamp |
+--------------------------+------------------------+------+--------+-----------------+
| 5a277319d6874c005b0db034 | succeeded (5s elapsed) | down | packs. | Wed, 06 Dec     |
|                          |                        | load | downlo | 2017 04:33:29   |
|                          |                        | pack | ad     | UTC             |
| 5a27731ed6874c005b0db036 | succeeded (1s elapsed) | make | packs. | Wed, 06 Dec     |
|                          |                        | a pr | virtua | 2017 04:33:34   |
|                          |                        | erun | lenv_p | UTC             |
|                          |                        |      | rerun  |                 |
| 5a277320d6874c005b0db039 | failed (46s elapsed)   | inst | packs. | Wed, 06 Dec     |
|                          |                        | all  | setup_ | 2017 04:33:36   |
|                          |                        | pack | virtua | UTC             |
|                          |                        | depe | lenv   |                 |
|                          |                        | nden |        |                 |
|                          |                        | cies |        |                 |
+--------------------------+------------------------+------+--------+-----------------+
root@9d76c52d1202:/#
```

**Comment by DoriftoShoes** [comment]
The README for this pack addresses this.  There are packages that need to be installed within the container before you can successfully install the ansible pack.  I was able to get it working after installing them.

**Comment by brainstorm** [comment]
Thanks @DoriftoShoes!
